name: Build docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs
  workflow_dispatch:
  
jobs:

  build-and-upload-artifact:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'setuptools<50.0'
          python -m pip install .[testing,docs]

      - name: Build docs
        run: |
          python docs/replace_description_text.py
          cd docs
          make html
          cd ..
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build/html
