
name: napari hub Preview Page # we use this name to find your preview page artifact, so don't change it!
# For more info on this action, see https://github.com/chanzuckerberg/napari-hub-preview-action/blob/main/action.yml

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  preview-page:
    name: Preview Page Deploy

    if: ${{ github.event.label.name == 'hub-preview' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: napari hub Preview Page Builder
        uses: chanzuckerberg/napari-hub-preview-action@v0.1.5
        with:
          hub-ref: main
